export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS"

export const GET_CORPORATIONS_SUCCESS = "GET_CORPORATIONS_SUCCESS"

export const GET_USER_SUCCESS = "GET_USER_SUCCESS"

export const GET_USER_BY_ID = "GET_USER_BY_ID"

export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS"

export const GET_NOTES_BY_ID = "GET_NOTES_BY_ID"